name: C Program Build, Test & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get install -y build-essential

    - name: Build program
      run: |
        gcc main.c sum.c -o program

    - name: Build test file
      run: |
        gcc test.c sum.c -o test_program

    - name: Run tests
      run: |
        ./test_program

    - name: Upload build artifact (deploy)
      uses: actions/upload-artifact@v4
      with:
        name: c-program-output
        path: program
